import '../hive/hive_adapters/country_model_adapter.dart';

class CountriesListHelper {
  static List<Map<String, String>> countriesList = [
    {'name': 'Afrikaans', 'code': 'af'},
    {'name': 'Albanian', 'code': 'sq'},
    {'name': 'Amharic', 'code': 'am'},
    {'name': 'Arabic', 'code': 'ar'},
    {'name': 'Armenian', 'code': 'hy'},
    {'name': 'Assamese', 'code': 'as'},
    {'name': 'Aymara', 'code': 'ay'},
    {'name': 'Azerbaijani', 'code': 'az'},
    {'name': 'Bambara', 'code': 'bm'},
    {'name': 'Basque', 'code': 'eu'},
    {'name': 'Belarusian', 'code': 'be'},
    {'name': 'Bengali', 'code': 'bn'},
    {'name': 'Bhojpuri', 'code': 'bho'},
    {'name': 'Bosnian', 'code': 'bs'},
    {'name': 'Bulgarian', 'code': 'bg'},
    {'name': 'Catalan', 'code': 'ca'},
    {'name': 'Cebuano', 'code': 'ceb'},
    {'name': 'Chinese', 'code': 'zh'},
    {'name': 'Chinese (Traditional)', 'code': 'zh-TW'},
    {'name': 'Corsican', 'code': 'co'},
    {'name': 'Croatian', 'code': 'hr'},
    {'name': 'Czech', 'code': 'cs'},
    {'name': 'Danish', 'code': 'da'},
    {'name': 'Dhivehi', 'code': 'dv'},
    {'name': 'Dogri', 'code': 'doi'},
    {'name': 'Dutch', 'code': 'nl'},
    {'name': 'English', 'code': 'en'},
    {'name': 'Esperanto', 'code': 'eo'},
    {'name': 'Estonian', 'code': 'et'},
    {'name': 'Ewe', 'code': 'ee'},
    {'name': 'Filipino', 'code': 'fil'},
    {'name': 'Finnish', 'code': 'fi'},
    {'name': 'French', 'code': 'fr'},
    {'name': 'Frisian', 'code': 'fy'},
    {'name': 'Galician', 'code': 'gl'},
    {'name': 'Georgian', 'code': 'ka'},
    {'name': 'German', 'code': 'de'},
    {'name': 'Greek', 'code': 'el'},
    {'name': 'Guarani', 'code': 'gn'},
    {'name': 'Gujarati', 'code': 'gu'},
    {'name': 'Haitian', 'code': 'ht'},
    {'name': 'Hausa', 'code': 'ha'},
    {'name': 'Hawaiian', 'code': 'haw'},
    {'name': 'Hebrew', 'code': 'iw'},
    {'name': 'Hindi', 'code': 'hi'},
    {'name': 'Hmong', 'code': 'hmn'},
    {'name': 'Hungarian', 'code': 'hu'},
    {'name': 'Icelandic', 'code': 'is'},
    {'name': 'Igbo', 'code': 'ig'},
    {'name': 'Ilocano', 'code': 'ilo'},
    {'name': 'Indonesian', 'code': 'id'},
    {'name': 'Irish', 'code': 'ga'},
    {'name': 'Italian', 'code': 'it'},
    {'name': 'Japanese', 'code': 'ja'},
    {'name': 'Javanese', 'code': 'jw'},
    {'name': 'Kannada', 'code': 'kn'},
    {'name': 'Kazakh', 'code': 'kk'},
    {'name': 'Khmer', 'code': 'km'},
    {'name': 'Kinyarwanda', 'code': 'rw'},
    {'name': 'Konkani', 'code': 'gom'},
    {'name': 'Korean', 'code': 'ko'},
    {'name': 'Krio', 'code': 'kri'},
    {'name': 'Kurdish', 'code': 'ku'},
    {'name': 'Kurdish', 'code': 'ckb'},
    {'name': 'Kyrgyz', 'code': 'ky'},
    {'name': 'Lao', 'code': 'lo'},
    {'name': 'Latin', 'code': 'la'},
    {'name': 'Latvian', 'code': 'lv'},
    {'name': 'Lingala', 'code': 'ln'},
    {'name': 'Lithuanian', 'code': 'lt'},
    {'name': 'Luganda', 'code': 'lg'},
    {'name': 'Luxembourgish', 'code': 'lb'},
    {'name': 'Macedonian', 'code': 'mk'},
    {'name': 'Maithili', 'code': 'mai'},
    {'name': 'Malagasy', 'code': 'mg'},
    {'name': 'Malay', 'code': 'ms'},
    {'name': 'Malayalam', 'code': 'ml'},
    {'name': 'Maltese', 'code': 'mt'},
    {'name': 'Maori', 'code': 'mi'},
    {'name': 'Marathi', 'code': 'mr'},
    {'name': 'Mizo', 'code': 'lus'},
    {'name': 'Mongolian', 'code': 'mn'},
    {'name': 'Myanmar', 'code': 'my'},
    {'name': 'Nepali', 'code': 'ne'},
    {'name': 'Norwegian', 'code': 'no'},
    {'name': 'Nyanja', 'code': 'ny'},
    {'name': 'Odia', 'code': 'or'},
    {'name': 'Oromo', 'code': 'om'},
    {'name': 'Pashto', 'code': 'ps'},
    {'name': 'Persian', 'code': 'fa'},
    {'name': 'Polish', 'code': 'pl'},
    {'name': 'Portuguese', 'code': 'pt'},
    {'name': 'Punjabi', 'code': 'pa'},
    {'name': 'Quechua', 'code': 'qu'},
    {'name': 'Romanian', 'code': 'ro'},
    {'name': 'Russian', 'code': 'ru'},
    {'name': 'Samoan', 'code': 'sm'},
    {'name': 'Sanskrit', 'code': 'sa'},
    {'name': 'Scots', 'code': 'gd'},
    {'name': 'Sepedi', 'code': 'nso'},
    {'name': 'Serbian', 'code': 'sr'},
    {'name': 'Sesotho', 'code': 'st'},
    {'name': 'Shona', 'code': 'sn'},
    {'name': 'Sindhi', 'code': 'sd'},
    {'name': 'Sinhala', 'code': 'si'},
    {'name': 'Slovak', 'code': 'sk'},
    {'name': 'Slovenian', 'code': 'sl'},
    {'name': 'Somali', 'code': 'so'},
    {'name': 'Spanish', 'code': 'es'},
    {'name': 'Sundanese', 'code': 'su'},
    {'name': 'Swahili', 'code': 'sw'},
    {'name': 'Swedish', 'code': 'sv'},
    {'name': 'Tagalog', 'code': 'tl'},
    {'name': 'Tajik', 'code': 'tg'},
    {'name': 'Tamil', 'code': 'ta'},
    {'name': 'Tatar', 'code': 'tt'},
    {'name': 'Telugu', 'code': 'te'},
    {'name': 'Thai', 'code': 'th'},
    {'name': 'Tigrinya', 'code': 'ti'},
    {'name': 'Tsonga', 'code': 'ts'},
    {'name': 'Turkish', 'code': 'tr'},
    {'name': 'Turkmen', 'code': 'tk'},
    {'name': 'Twi', 'code': 'ak'},
    {'name': 'Ukrainian', 'code': 'uk'},
    {'name': 'Urdu', 'code': 'ur'},
    {'name': 'Uyghur', 'code': 'ug'},
    {'name': 'Uzbek', 'code': 'uz'},
    {'name': 'Vietnamese', 'code': 'vi'},
    {'name': 'Welsh', 'code': 'cy'},
    {'name': 'Xhosa', 'code': 'xh'},
    {'name': 'Yiddish', 'code': 'yi'},
    {'name': 'Yoruba', 'code': 'yo'},
    {'name': 'Zulu', 'code': 'zu'},
  ];

  static Map<String, String> languagesFromPackage = {
    'auto': 'Automatic',
    'af': 'Afrikaans',
    'sq': 'Albanian',
    'am': 'Amharic',
    'ar': 'Arabic',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    'eu': 'Basque',
    'be': 'Belarusian',
    'bn': 'Bengali',
    'bs': 'Bosnian',
    'bg': 'Bulgarian',
    'ca': 'Catalan',
    'ceb': 'Cebuano',
    'ny': 'Chichewa',
    'zh-cn': 'Chinese Simplified',
    'zh-tw': 'Chinese Traditional',
    'co': 'Corsican',
    'hr': 'Croatian',
    'cs': 'Czech',
    'da': 'Danish',
    'nl': 'Dutch',
    'en': 'English',
    'eo': 'Esperanto',
    'et': 'Estonian',
    'tl': 'Filipino',
    'fi': 'Finnish',
    'fr': 'French',
    'fy': 'Frisian',
    'gl': 'Galician',
    'ka': 'Georgian',
    'de': 'German',
    'el': 'Greek',
    'gu': 'Gujarati',
    'ht': 'Haitian Creole',
    'ha': 'Hausa',
    'haw': 'Hawaiian',
    'iw': 'Hebrew',
    'hi': 'Hindi',
    'hmn': 'Hmong',
    'hu': 'Hungarian',
    'is': 'Icelandic',
    'ig': 'Igbo',
    'id': 'Indonesian',
    'ga': 'Irish',
    'it': 'Italian',
    'ja': 'Japanese',
    'jw': 'Javanese',
    'kn': 'Kannada',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'ko': 'Korean',
    'ku': 'Kurdish (Kurmanji)',
    'ky': 'Kyrgyz',
    'lo': 'Lao',
    'la': 'Latin',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'lb': 'Luxembourgish',
    'mk': 'Macedonian',
    'mg': 'Malagasy',
    'ms': 'Malay',
    'ml': 'Malayalam',
    'mt': 'Maltese',
    'mi': 'Maori',
    'mr': 'Marathi',
    'mn': 'Mongolian',
    'my': 'Myanmar (Burmese)',
    'ne': 'Nepali',
    'no': 'Norwegian',
    'ps': 'Pashto',
    'fa': 'Persian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'pa': 'Punjabi',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sm': 'Samoan',
    'gd': 'Scots Gaelic',
    'sr': 'Serbian',
    'st': 'Sesotho',
    'sn': 'Shona',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'so': 'Somali',
    'es': 'Spanish',
    'su': 'Sundanese',
    'sw': 'Swahili',
    'sv': 'Swedish',
    'tg': 'Tajik',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    'ug': 'Uyghur',
    'vi': 'Vietnamese',
    'cy': 'Welsh',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'zu': 'Zulu'
  };

  static List<LanguageModel> countries = [];

  static void setCountriesList() {
    countries.clear();
    languagesFromPackage.forEach((key, value) {
      countries.add(LanguageModel(code: key, name: value));
    });

    // for (var element in countriesList) {
    //   countries.add(
    //     CountryModel(code: element['code']!, name: element['name']!),
    //   );
    // }
  }
}
